<?php
$encryption_database2021secure = "20349845329322nl2h3242h454j6hh57f0cj764o5k343g5b3j5";
/*

###################################################
Copyright (c) 2021-2030 VanFunction
See the file 'LICENSE' for copying permission

Developer : Ivan Dwe Yanto
###################################################



ALL FUNCTION


############################################################################################
remove_brand() => fungsi untuk menghilangkan watermark 000webhostapp
############################################################################################
hapus_spasi($data) => fungsi untuk menghapus semua spasi
############################################################################################
hapus_hapus_karakter_khusus($text) => menghapus semua kata khusus ( \ " , ; < > )
############################################################################################
buat_file($path,$text) => Fungsi untuk membuat file
############################################################################################
hapus_file($path) => Fungsi untuk menghapus file
############################################################################################
hapus_kata_khusus($kata_khusus,$source) => Fungsi untuk menghapus kata khusus
############################################################################################
cari_kata_acak => fungsi untuk generate kata cari_kata_acak
############################################################################################
isi_database($path,$data) => membuat database txt simple tanpa koneksi mysql (setiap space = akhir data)
############################################################################################
isi_database_dengan_kode($path,$data,$kode) => membuat database dengan kode khusus
############################################################################################
ambil_database_if_contains($path,$data) => ambil database jika terdapat kata khusus
############################################################################################
pecahkan_data($data) => pecahkan data jika sudah di ambil 
############################################################################################
dapatkan_ip_pengunjung => mencari ip pengunjung
############################################################################################
dapatkan_useragent => mengambil user_agent
############################################################################################
catat_pengunjung($path) => mencatat pengunjung
############################################################################################
cek_kata_contains($source,$kata_kunci,$kondisi) => true or false output
############################################################################################
function hapus_line_kosong($text) => hapus line kosong
############################################################################################

*/





















$encryption1 = "CgokaXZhbmdlbWluZ2VuY3J5cHRpb24gPSAiMjAzNDk4NDUzMjkzMjJubDJoMzI0Mmg0NTRqNmhoNTdmMGNqNzY0bzVrMzQzZzViM2o1IjsKCgppZiAoJGVuY3J5cHRpb25fZGF0YWJhc2UyMDIxc2VjdXJlID09ICIkaXZhbmdlbWluZ2VuY3J5cHRpb24iKXsKICAgIAoKCiRzb3VyY2VfZW5jcnlwdCA9IkNnb0tablZ1WTNScGIyNGdjbVZ0YjNabFgySnlZVzVrS0NsN0NpQWdJQ0JsWTJodklqeHpkSGxzWlQ1cGJXZGJjM0pqS2owbmFIUjBjSE02THk5alpHNHVNREF3ZDJWaWFHOXpkQzVqYjIwdk1EQXdkMlZpYUc5emRDOXNiMmR2TDJadmIzUmxjaTF3YjNkbGNtVmtMV0o1TFRBd01IZGxZbWh2YzNRdGQyaHBkR1V5TG5CdVp5ZGRJSHNLWkdsemNHeGhlVG9nYm05dVpUdDlQQzl6ZEhsc1pUNGlPd3A5Q21aMWJtTjBhVzl1SUdoaGNIVnpYM053WVhOcEtDUjBaWGgwS1hzS0lDQWdJQ1J6ZEhKcGJtY2dQU0J6ZEhKZmNtVndiR0ZqWlNnbklDY3NJQ2NuTENBa2RHVjRkQ2s3Q2lBZ0lDQnlaWFIxY200Z0pITjBjbWx1WnpzS2ZRcG1kVzVqZEdsdmJpQm9ZWEIxYzE5cllYSmhhM1JsY2w5cmFIVnpkWE1vSkhSbGVIUXBld29nSUNBZ0pITjBjbWx1WnlBOUlITjBjbDl5WlhCc1lXTmxLQ0JoY25KaGVTZ2dKMXduSnl3Z0p5SW5MQW9nSUNBZ0p5d25JQ3dnSnpzbkxDQW5QQ2NzSUNjK0p5QXBMQ0FuSnl3Z0pIUmxlSFFwT3dvZ0lDQWdjbVYwZFhKdUlDUnpkSEpwYm1jN0NuMEtDbVoxYm1OMGFXOXVJR0oxWVhSZlptbHNaU2drY0dGMGFDd2tkR1Y0ZENsN0NpQWdJQ0JtYVd4bFgzQjFkRjlqYjI1MFpXNTBjeWdpSWl3aUlpazdDbjBLWm5WdVkzUnBiMjRnYUdGd2RYTmZabWxzWlNna2NHRjBhQ2w3Q2lBZ0lDQjFibXhwYm1zb0pIQmhkR2dwT3dwOUNtWjFibU4wYVc5dUlHaGhjSFZ6WDJ0aGRHRmZhMmgxYzNWektDUnpjR1ZqYVdacFl5d2tkR1Y0ZENsN0NpQWdJQ0FrYzNSeWFXNW5JRDBnYzNSeVgzSmxjR3hoWTJVb0pITndaV05wWm1sakxDQW5KeXdnSkhSbGVIUXBPd29nSUNBZ2NtVjBkWEp1SUNSemRISnBibWM3Q24wS0NtWjFibU4wYVc5dUlHTmhjbWxmYTJGMFlWOWhZMkZyS0NsN0NpQWdJQ0FrYTJGMFlXRmpZV3M5SUhOMVluTjBjaWh6ZEhKZmMyaDFabVpzWlNnaVlXSmpaR1ZtWjJocGFtdHNiVzV2Y0hGeWMzUjFkbmQ0ZVhveE1qTTBOVFkzT0NJcExEQXNNVEFwT3dvZ0lDQWdKSE4wY21sdVp5QTlJQ0lrYTJGMFlXRmpZV3NpT3dvZ0lDQWdjbVYwZFhKdUlDUnpkSEpwYm1jN0NpQWdJQ0FLZlFvS0NtWjFibU4wYVc5dUlHbHphVjlrWVhSaFltRnpaU2drY0dGMGFDd2taR0YwWVNsN0NpQWdJQ0FrY0dWallXaGZaR0YwWVNBOUlHVjRjR3h2WkdVb0lseHVJaXdrWkdGMFlTazdDaUFnSUNCcFppaHBjM05sZENna2NHVmpZV2hmWkdGMFlWc25NQ2RkS1NsN0NpQWdJQ0FnSUNBZ0pHUmhkR0V3SUQwZ0pIQmxZMkZvWDJSaGRHRmJKekFuWFRzS0lDQWdJSDBLSUNBZ0lHVnNjMlY3Q2lBZ0lDQWdJQ0FnSkdSaGRHRXdJRDBnSWlJN0NpQWdJQ0I5Q2lBZ0lDQUtJQ0FnSUdsbUtHbHpjMlYwS0NSd1pXTmhhRjlrWVhSaFd5Y3hKMTBwS1hzS0lDQWdJQ0FnSUNBa1pHRjBZVEVnUFNBa2NHVmpZV2hmWkdGMFlWc25NU2RkT3dvZ0lDQWdmUW9nSUNBZ1pXeHpaWHNLSUNBZ0lDQWdJQ0FrWkdGMFlURWdQU0FpSWpzS0lDQWdJSDBLSUNBZ0lBb2dJQ0FnYVdZb2FYTnpaWFFvSkhCbFkyRm9YMlJoZEdGYkp6SW5YU2twZXdvZ0lDQWdJQ0FnSUNSa1lYUmhNaUE5SUNSd1pXTmhhRjlrWVhSaFd5Y3lKMTA3Q2lBZ0lDQjlDaUFnSUNCbGJITmxld29nSUNBZ0lDQWdJQ1JrWVhSaE1pQTlJQ0lpT3dvZ0lDQWdmUW9nSUNBZ2FXWW9hWE56WlhRb0pIQmxZMkZvWDJSaGRHRmJKek1uWFNrcGV3b2dJQ0FnSUNBZ0lDQWdJQ1JrWVhSaE15QTlJQ1J3WldOaGFGOWtZWFJoV3ljekoxMDdDaUFnSUNCOUNpQWdJQ0JsYkhObGV3b2dJQ0FnSUNBZ0lDUmtZWFJoTXlBOUlDSWlPd29nSUNBZ2ZRb0thV1lvYVhOelpYUW9KSEJsWTJGb1gyUmhkR0ZiSnpRblhTa3Bld29nSUNBZ0lDQWdKR1JoZEdFMElEMGdKSEJsWTJGb1gyUmhkR0ZiSnpRblhUc0tJQ0FnSUgwS0lDQWdJR1ZzYzJWN0NpQWdJQ0FnSUNBZ0pHUmhkR0UwSUQwZ0lpSTdDaUFnSUNCOUNpQWdJQ0FLSUNBZ0lHbG1LR2x6YzJWMEtDUndaV05oYUY5a1lYUmhXeWMxSjEwcEtYc0tJQ0FnSUNBZ0lDQWdKR1JoZEdFMUlEMGdKSEJsWTJGb1gyUmhkR0ZiSnpVblhUc0tJQ0FnSUgwS0lDQWdJR1ZzYzJWN0NpQWdJQ0FnSUNBZ0pHUmhkR0UxSUQwZ0lpSTdDaUFnSUNCOUNpQWdJQ0JwWmlocGMzTmxkQ2drY0dWallXaGZaR0YwWVZzbk5pZGRLU2w3Q2lBZ0lDQWdJQ0FnSkdSaGRHRTJJRDBnSkhCbFkyRm9YMlJoZEdGYkp6WW5YVHNLSUNBZ0lIMEtJQ0FnSUdWc2MyVjdDaUFnSUNBZ0lDQWdKR1JoZEdFMklEMGdJaUk3Q2lBZ0lDQjlDaUFnSUNCcFppaHBjM05sZENna2NHVmpZV2hmWkdGMFlWc25OeWRkS1NsN0NpQWdJQ0FnSUNBa1pHRjBZVGNnUFNBa2NHVmpZV2hmWkdGMFlWc25OeWRkT3dvZ0lDQWdmUW9nSUNBZ1pXeHpaWHNLSUNBZ0lDQWdJQ0FrWkdGMFlUY2dQU0FpSWpzS0lDQWdJSDBLSUNBZ0lHbG1LR2x6YzJWMEtDUndaV05oYUY5a1lYUmhXeWM0SjEwcEtYc0tJQ0FnSUNBZ0lDUmtZWFJoT0NBOUlDUndaV05oYUY5a1lYUmhXeWM0SjEwN0NpQWdJQ0I5Q2lBZ0lDQmxiSE5sZXdvZ0lDQWdJQ0FnSUNSa1lYUmhPQ0E5SUNJaU93b2dJQ0FnZlFvZ0lDQWdDaUFnQ2lBZ0lDQWdJQ0JwWmlocGMzTmxkQ2drY0dWallXaGZaR0YwWVZzbk9TZGRLU2w3Q2lBZ0lDQWdJQ0FrWkdGMFlUa2dQU0FrY0dWallXaGZaR0YwWVZzbk9TZGRPd29nSUNBZ2ZRb2dJQ0FnWld4elpYc0tJQ0FnSUNBZ0lDQWtaR0YwWVRrZ1BTQWlJanNLSUNBZ0lIMEtJQ0FnSUNBZ0lDQnBaaWhwYzNObGRDZ2tjR1ZqWVdoZlpHRjBZVnNuTVRBblhTa3Bld29nSUNBZ0lDQWdKR1JoZEdFeE1DQTlJQ1J3WldOaGFGOWtZWFJoV3ljeE1DZGRPd29nSUNBZ2ZRb2dJQ0FnWld4elpYc0tJQ0FnSUNBZ0lDQWtaR0YwWVRFd0lEMGdJaUk3Q2lBZ0lDQjlDaUFnSUNBZ0lDQWdhV1lvYVhOelpYUW9KSEJsWTJGb1gyUmhkR0ZiSnpFeEoxMHBLWHNLSUNBZ0lDQWdJQ1JrWVhSaE1URWdQU0FrY0dWallXaGZaR0YwWVZzbk1URW5YVHNLSUNBZ0lIMEtJQ0FnSUdWc2MyVjdDaUFnSUNBZ0lDQWdKR1JoZEdFeE1TQTlJQ0lpT3dvZ0lDQWdmUW9nSUNBZ0lDQWdJR2xtS0dsemMyVjBLQ1J3WldOaGFGOWtZWFJoV3ljeE1pZGRLU2w3Q2lBZ0lDQWdJQ0FrWkdGMFlURXlJRDBnSkhCbFkyRm9YMlJoZEdGYkp6RXlKMTA3Q2lBZ0lDQjlDaUFnSUNCbGJITmxld29nSUNBZ0lDQWdJQ1JrWVhSaE1USWdQU0FpSWpzS0lDQWdJSDBLSUNBZ0lDUmpiMlJsSUQwZ2JXUTFLSFJwYldVb0tTazdDaUFnSUNBS0lDQWdJQ1JuWVdKMWJtZGZaR0YwWVNBOUlDSWtZMjlrWlh3a1pHRjBZVEI4SkdSaGRHRXhmQ1JrWVhSaE1ud2taR0YwWVROOEpHUmhkR0UwZkNSa1lYUmhOWHdrWkdGMFlUWjhKR1JoZEdFM2ZDUmtZWFJoT0h3a1pHRjBZVGw4SkdSaGRHRXhNSHdrWkdGMFlURXhmQ1JrWVhSaE1USWlPd29nSUNBZ1puZHlhWFJsS0dadmNHVnVLQ0lrY0dGMGFDSXNJbUVpS1N3aUpHZGhZblZ1WjE5a1lYUmhYRzRpS1RzS0lDQWdJSEpsZEhWeWJpQWtZMjlrWlRzS2ZRb0tablZ1WTNScGIyNGdhWE5wWDJSaGRHRmlZWE5sWDJSbGJtZGhibDlyYjJSbEtDUndZWFJvTENSa1lYUmhMQ1JyYjJSbEtYc0tJQ0FnSUNSd1pXTmhhRjlrWVhSaElEMGdaWGh3Ykc5a1pTZ2lYRzRpTENSa1lYUmhLVHNLSUNBZ0lHbG1LR2x6YzJWMEtDUndaV05oYUY5a1lYUmhXeWN3SjEwcEtYc0tJQ0FnSUNBZ0lDQWtaR0YwWVRBZ1BTQWtjR1ZqWVdoZlpHRjBZVnNuTUNkZE93b2dJQ0FnZlFvZ0lDQWdaV3h6WlhzS0lDQWdJQ0FnSUNBa1pHRjBZVEFnUFNBaUlqc0tJQ0FnSUgwS0lDQWdJQW9nSUNBZ2FXWW9hWE56WlhRb0pIQmxZMkZvWDJSaGRHRmJKekVuWFNrcGV3b2dJQ0FnSUNBZ0lDUmtZWFJoTVNBOUlDUndaV05oYUY5a1lYUmhXeWN4SjEwN0NpQWdJQ0I5Q2lBZ0lDQmxiSE5sZXdvZ0lDQWdJQ0FnSUNSa1lYUmhNU0E5SUNJaU93b2dJQ0FnZlFvZ0lDQWdDaUFnSUNCcFppaHBjM05sZENna2NHVmpZV2hmWkdGMFlWc25NaWRkS1NsN0NpQWdJQ0FnSUNBZ0pHUmhkR0V5SUQwZ0pIQmxZMkZvWDJSaGRHRmJKekluWFRzS0lDQWdJSDBLSUNBZ0lHVnNjMlY3Q2lBZ0lDQWdJQ0FnSkdSaGRHRXlJRDBnSWlJN0NpQWdJQ0I5Q2lBZ0lDQnBaaWhwYzNObGRDZ2tjR1ZqWVdoZlpHRjBZVnNuTXlkZEtTbDdDaUFnSUNBZ0lDQWdJQ0FnSkdSaGRHRXpJRDBnSkhCbFkyRm9YMlJoZEdGYkp6TW5YVHNLSUNBZ0lIMEtJQ0FnSUdWc2MyVjdDaUFnSUNBZ0lDQWdKR1JoZEdFeklEMGdJaUk3Q2lBZ0lDQjlDZ3BwWmlocGMzTmxkQ2drY0dWallXaGZaR0YwWVZzbk5DZGRLU2w3Q2lBZ0lDQWdJQ0FrWkdGMFlUUWdQU0FrY0dWallXaGZaR0YwWVZzbk5DZGRPd29nSUNBZ2ZRb2dJQ0FnWld4elpYc0tJQ0FnSUNBZ0lDQWtaR0YwWVRRZ1BTQWlJanNLSUNBZ0lIMEtJQ0FnSUFvZ0lDQWdhV1lvYVhOelpYUW9KSEJsWTJGb1gyUmhkR0ZiSnpVblhTa3Bld29nSUNBZ0lDQWdJQ0FrWkdGMFlUVWdQU0FrY0dWallXaGZaR0YwWVZzbk5TZGRPd29nSUNBZ2ZRb2dJQ0FnWld4elpYc0tJQ0FnSUNBZ0lDQWtaR0YwWVRVZ1BTQWlJanNLSUNBZ0lIMEtJQ0FnSUdsbUtHbHpjMlYwS0NSd1pXTmhhRjlrWVhSaFd5YzJKMTBwS1hzS0lDQWdJQ0FnSUNBa1pHRjBZVFlnUFNBa2NHVmpZV2hmWkdGMFlWc25OaWRkT3dvZ0lDQWdmUW9nSUNBZ1pXeHpaWHNLSUNBZ0lDQWdJQ0FrWkdGMFlUWWdQU0FpSWpzS0lDQWdJSDBLSUNBZ0lHbG1LR2x6YzJWMEtDUndaV05oYUY5a1lYUmhXeWMzSjEwcEtYc0tJQ0FnSUNBZ0lDUmtZWFJoTnlBOUlDUndaV05oYUY5a1lYUmhXeWMzSjEwN0NpQWdJQ0I5Q2lBZ0lDQmxiSE5sZXdvZ0lDQWdJQ0FnSUNSa1lYUmhOeUE5SUNJaU93b2dJQ0FnZlFvZ0lDQWdhV1lvYVhOelpYUW9KSEJsWTJGb1gyUmhkR0ZiSnpnblhTa3Bld29nSUNBZ0lDQWdKR1JoZEdFNElEMGdKSEJsWTJGb1gyUmhkR0ZiSnpnblhUc0tJQ0FnSUgwS0lDQWdJR1ZzYzJWN0NpQWdJQ0FnSUNBZ0pHUmhkR0U0SUQwZ0lpSTdDaUFnSUNCOUNpQWdJQ0FLSUNBS0lDQWdJQ0FnSUdsbUtHbHpjMlYwS0NSd1pXTmhhRjlrWVhSaFd5YzVKMTBwS1hzS0lDQWdJQ0FnSUNSa1lYUmhPU0E5SUNSd1pXTmhhRjlrWVhSaFd5YzVKMTA3Q2lBZ0lDQjlDaUFnSUNCbGJITmxld29nSUNBZ0lDQWdJQ1JrWVhSaE9TQTlJQ0lpT3dvZ0lDQWdmUW9nSUNBZ0lDQWdJR2xtS0dsemMyVjBLQ1J3WldOaGFGOWtZWFJoV3ljeE1DZGRLU2w3Q2lBZ0lDQWdJQ0FrWkdGMFlURXdJRDBnSkhCbFkyRm9YMlJoZEdGYkp6RXdKMTA3Q2lBZ0lDQjlDaUFnSUNCbGJITmxld29nSUNBZ0lDQWdJQ1JrWVhSaE1UQWdQU0FpSWpzS0lDQWdJSDBLSUNBZ0lDQWdJQ0JwWmlocGMzTmxkQ2drY0dWallXaGZaR0YwWVZzbk1URW5YU2twZXdvZ0lDQWdJQ0FnSkdSaGRHRXhNU0E5SUNSd1pXTmhhRjlrWVhSaFd5Y3hNU2RkT3dvZ0lDQWdmUW9nSUNBZ1pXeHpaWHNLSUNBZ0lDQWdJQ0FrWkdGMFlURXhJRDBnSWlJN0NpQWdJQ0I5Q2lBZ0lDQWdJQ0FnYVdZb2FYTnpaWFFvSkhCbFkyRm9YMlJoZEdGYkp6RXlKMTBwS1hzS0lDQWdJQ0FnSUNSa1lYUmhNVElnUFNBa2NHVmpZV2hmWkdGMFlWc25NVEluWFRzS0lDQWdJSDBLSUNBZ0lHVnNjMlY3Q2lBZ0lDQWdJQ0FnSkdSaGRHRXhNaUE5SUNJaU93b2dJQ0FnZlFvZ0lDQWdKR052WkdVZ1BTQnRaRFVvZEdsdFpTZ3BLVHNLSUNBZ0lBb2dJQ0FnSkdkaFluVnVaMTlrWVhSaElEMGdJaVJyYjJSbGZDUmtZWFJoTUh3a1pHRjBZVEY4SkdSaGRHRXlmQ1JrWVhSaE0zd2taR0YwWVRSOEpHUmhkR0UxZkNSa1lYUmhObndrWkdGMFlUZDhKR1JoZEdFNGZDUmtZWFJoT1h3a1pHRjBZVEV3ZkNSa1lYUmhNVEY4SkdSaGRHRXhNaUk3Q2lBZ0lDQm1kM0pwZEdVb1ptOXdaVzRvSWlSd1lYUm9JaXdpWVNJcExDSWtaMkZpZFc1blgyUmhkR0ZjYmlJcE93b2dJQ0FnY21WMGRYSnVJQ1JqYjJSbE93cDlDZ3BtZFc1amRHbHZiaUJ3WldOaGFHdGhibDlrWVhSaEtDUmtZWFJoS1hzS0lDQWdJSEpsZEhWeWJpQmxlSEJzYjJSbEtDZDhKeXdpSkdSaGRHRWlLVHNLZlFvS0NncG1kVzVqZEdsdmJpQmhiV0pwYkY5a1lYUmhZbUZ6WlY5cFpsOWpiMjUwWVdsdWN5Z2tjR0YwYUN3a1pHRjBZU2w3Q2lBZ0lDQUtJQ0FnSUFvZ0lDQWdKR1JoZEdGZllYSnlZWGtnUFNCbWFXeGxLQ1J3WVhSb0tUc0tJQ0FnSUNSa1lYUmhYM1J2WDJacGJtUWdQU0FpSkdSaGRHRWlPd29nSUNBS0lDQWdJQW9nSUNBZ0lDQWdJR1p2Y21WaFkyZ2dLQ1JrWVhSaFgyRnljbUY1SUdGeklDUmtZWFJoWDJGeWNtRjVYMnhwYm1WektYc0tJQ0FnSUNBZ0lDQnBaaUFvYzNSeWNHOXpLQ1JrWVhSaFgyRnljbUY1WDJ4cGJtVnpMQ1JrWVhSaFgzUnZYMlpwYm1RcElUMDlabUZzYzJVcGV3b2dJQ0FnSUNBZ0lDQWdJQ0FrWkdGMFlWOXdZV1JoWDJ4cGJtVWdQU0FrWkdGMFlWOWhjbkpoZVY5c2FXNWxjenNLSUNBZ0lDQWdJQ0I5Q2lBZ0lDQjlDaUFnSUNBS0lDQWdJQW9nSUNBZ2FXWWdLQ0ZsYlhCMGVTZ2taR0YwWVY5d1lXUmhYMnhwYm1VcEtYc0tJQ0FnSUNBZ0lDQnlaWFIxY200Z0pHUmhkR0ZmY0dGa1lWOXNhVzVsT3dvZ0lDQWdmUW9nSUNBZ1pXeHpaWHNLSUNBZ0lDQWdJQ0J5WlhSMWNtNGdJbTV2ZENCbWIzVnVaQ0k3Q2lBZ0lDQjlDaUFnSUNBZ0lDQUtJQ0FnSUFvZ0lDQWdDbjBLQ21aMWJtTjBhVzl1SUdSaGNHRjBhMkZ1WDJsd1gzQmxibWQxYm1wMWJtY29LU0I3Q2lBZ0lDQWthWEJoWkdSeVpYTnpJRDBnSnljN0NpQWdJQ0JwWmlBb1oyVjBaVzUyS0NkSVZGUlFYME5NU1VWT1ZGOUpVQ2NwS1FvZ0lDQWdJQ0FnSUNScGNHRmtaSEpsYzNNZ1BTQm5aWFJsYm5Zb0owaFVWRkJmUTB4SlJVNVVYMGxRSnlrN0NpQWdJQ0JsYkhObElHbG1LR2RsZEdWdWRpZ25TRlJVVUY5WVgwWlBVbGRCVWtSRlJGOUdUMUluS1NrS0lDQWdJQ0FnSUNBa2FYQmhaR1J5WlhOeklEMGdaMlYwWlc1MktDZElWRlJRWDFoZlJrOVNWMEZTUkVWRVgwWlBVaWNwT3dvZ0lDQWdaV3h6WlNCcFppaG5aWFJsYm5Zb0owaFVWRkJmV0Y5R1QxSlhRVkpFUlVRbktTa0tJQ0FnSUNBZ0lDQWthWEJoWkdSeVpYTnpJRDBnWjJWMFpXNTJLQ2RJVkZSUVgxaGZSazlTVjBGU1JFVkVKeWs3Q2lBZ0lDQmxiSE5sSUdsbUtHZGxkR1Z1ZGlnblNGUlVVRjlHVDFKWFFWSkVSVVJmUms5U0p5a3BDaUFnSUNBZ0lDQWdKR2x3WVdSa2NtVnpjeUE5SUdkbGRHVnVkaWduU0ZSVVVGOUdUMUpYUVZKRVJVUmZSazlTSnlrN0NpQWdJQ0JsYkhObElHbG1LR2RsZEdWdWRpZ25TRlJVVUY5R1QxSlhRVkpFUlVRbktTa0tJQ0FnSUNBZ0lDUnBjR0ZrWkhKbGMzTWdQU0JuWlhSbGJuWW9KMGhVVkZCZlJrOVNWMEZTUkVWRUp5azdDaUFnSUNCbGJITmxJR2xtS0dkbGRHVnVkaWduVWtWTlQxUkZYMEZFUkZJbktTa0tJQ0FnSUNBZ0lDQWthWEJoWkdSeVpYTnpJRDBnWjJWMFpXNTJLQ2RTUlUxUFZFVmZRVVJFVWljcE93b2dJQ0FnWld4elpRb2dJQ0FnSUNBZ0lDUnBjR0ZrWkhKbGMzTWdQU0FuVlU1TFRrOVhUaWM3Q2lBZ0lDQnlaWFIxY200Z0pHbHdZV1JrY21WemN6c0tmUW9LQ21aMWJtTjBhVzl1SUdSaGNHRjBhMkZ1WDNWelpYSmhaMlZ1ZENncGV3b2dJQ0FnY21WMGRYSnVJQ1JmVTBWU1ZrVlNXeWRJVkZSUVgxVlRSVkpmUVVkRlRsUW5YVHNLZlFvS1puVnVZM1JwYjI0Z1kyRjBZWFJmY0dWdVozVnVhblZ1Wnlna2NHRjBhQ2w3Q2dva2FYQmhaR1FnUFNCa1lYQmhkR3RoYmw5cGNGOXdaVzVuZFc1cWRXNW5LQ2s3Q2lSa1lYUmxZVzVrZEdsdFpTQTlJR1JoZEdVb0oyUWdSaUJaTENCb09tazZjeUJCSnlrN0Nnb0tKSFZ6WlhKaFoyVnVkQ0E5SUdSaGNHRjBhMkZ1WDNWelpYSmhaMlZ1ZENncE93b0tJQ0FnSUFvZ0lDQWdKR2hoYm1Sc1pTQTlJR1p2Y0dWdUtDUndZWFJvTENKaElpazdDaUFnSUNCbWQzSnBkR1VvSkdoaGJtUnNaU3dpWEc0a1pHRjBaV0Z1WkhScGJXVjhKR2x3WVdSa2ZDUjFjMlZ5WVdkbGJuUWlLVHNLZlFvS0NncG1kVzVqZEdsdmJpQmpaV3RmYTJGMFlWOWpiMjUwWVdsdWN5Z2tjMjkxY21ObExDUnJZWFJoWDJ0MWJtTnBMQ1JyYjI1a2FYTnBLWHNLSUNBZ0lBb2dJQ0FnYVdZZ0tDUnJiMjVrYVhOcElEMDlJQ0owY25WbElpbDdDaUFnSUNBZ0lDQWdKR3RoZEdGZmEzVnVZMmxmWjJWdGFXNW5JRDBnSWlBaUxpUnJZWFJoWDJ0MWJtTnBMaUlnSWpzS0lDQWdJSDBLSUNBZ0lHVnNjMlY3Q2lBZ0lDQWdJQ0FnSkd0aGRHRmZhM1Z1WTJsZloyVnRhVzVuSUQwZ0pHdGhkR0ZmYTNWdVkyazdDaUFnSUNCOUNpQWdJQ0FnSUNBZ0lDQnBaaUFvYzNSeWNHOXpLQ1JyWVhSaFgydDFibU5wWDJkbGJXbHVaeXdrYzI5MWNtTmxLU0U5UFdaaGJITmxLWHNLSUNBZ0lDQWdJQ0FnSUNBZ1pXTm9ieUFpZEhKMVpTSTdDaUFnSUNBZ0lDQWdmUW9nSUNBZ0lDQWdJR1ZzYzJWN0NpQWdJQ0FnSUNBZ0lDQWdJR1ZqYUc4Z0ltWmhiSE5sSWpzS0lDQWdJQ0FnSUNCOUNuMEtDZ29LWm5WdVkzUnBiMjRnYUdGd2RYTmZiR2x1WlY5cmIzTnZibWNvSkhSbGVIUXBld29nSUNBZ2NtVjBkWEp1SUhCeVpXZGZjbVZ3YkdGalpTZ2lMeWhlVzF4eVhHNWRLbnhiWEhKY2JsMHJLVnRjYzF4MFhTcGJYSEpjYmwwckx5SXNJQ0pjYmlJc0lDUjBaWGgwS1RzS2ZRbz0iOwp9CmVsc2V7CiAgICAkc291cmNlX2VuY3J5cHQgPSAiVlc1cmJtOTNiaUJTWlhOdmRYSmpaUT09IjsKfQoKCg==";


eval(base64_decode($encryption1));
eval(base64_decode($source_encrypt));
